### ISSUE TITLE
work with d435 camera only

### ISSUE THREAD

**Issue by rosanom** [chrissunny94/t265_robot_navigation#1]
Hi! I've seen your project's video on youtube, it's really interesting! Thank you for sharing your project on github.
Currently I have a realsense d435i and I'm trying to use the realsense official SLAM solution in order to map and navigate consequently, but I'm struggling with the navigation part. 
Your code seems simple and clear and I'm planning to try it. Do you think it's possible to just use a d435 WITHOUT the t265 camera? In that case, should I change some parameters or portion of codes in your implementation?

Thank you in advance!

**Comment by chrissunny94** [comment]
If you are not intending to use the T265 camera then you will need to run some Visual Slam algorithm to provide you with the Pose  . I am using T265 specifically because just such an algorithm is running onboard . So , essentially the T265 directly gives me the Odometry .

Yes , you can use parts of my code , 
https://github.com/chrissunny94/t265_robot_navigation/blob/master/occupancy/src/occupancy_node.cpp#L128 , Here you need to change the topic name to what ever Odometry topic the Visual Slam algorithm of your choice puts out . 

You will also , you will need to do similar alterations to the move_base params .

**Comment by chrissunny94** [comment]
I will upload a repo using a pipeline setup with ORB_SLAM2 or some other visual slam algorithms .

I am closing this story. Thanks
